### PR TITLE
Fix: "except" field in Star macro handles cross db column casing

### PR DESCRIPTION
**Pull request by danieldiamond**
This is a:
- [ ] bug fix PR with no breaking changes — please ensure the base branch is `master`
- [x] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [x] Redshift
    - [x] Snowflake
- [ ] I have "dispatched" any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have added an entry to CHANGELOG.md

### CODE REVIEW

**Comment by danieldiamond** [comment]
@jtcohen6 failing integration tests appear to be unrelated to this PR. Tried pinning dbt_requirements in integration_tests project even though it inherits from root directory but didn't help. I _think_ it's occurring in `run_tests.sh` but unable to trace. 

Anyways hoping this PR can make it through. Let me know if any additional information is required.

```sh
Error encountered in /home/********/project/integration_tests/dbt_modules/dbt_utils
Running with dbt=0.21.0-b1
Encountered an error:
Runtime Error
  Failed to read package: Runtime Error
    This version of dbt is not supported with the 'dbt_utils' package.
      Installed version of dbt: =0.21.0-b1
      Required version of dbt for 'dbt_utils': ['>=0.20.0', '<0.21.0']
    Check the requirements for the 'dbt_utils' package, or run dbt again with --no-version-check
```

**Comment by jtcohen6** [comment]
@danieldiamond This is related to how we run `dbt-utils` integration tests with the latest prerelease version of dbt, and we just released v0.21.0-b1 yesterday. As it is, there aren't going to be any breaking changes to `dbt-utils` in v0.21, so we can bump the `require-dbt-version` boundary accordingly.

**Comment by danieldiamond** [comment]
cc'ing @jtcohen6 @annafil unable to add reviewers but would like to see this get merged in if possible

**Comment by reidwil-jb** [comment]
#403 If one of our PR's gets merged, we should close the other @danieldiamond

**Comment by danieldiamond** [comment]
niiice @reidwil-jb didnt realize that `col.column|lower not in except|lower` mapping can apply to both str and list objects 🔥

**Comment by reidwil-jb** [comment]
@danieldiamond yep! Two solutions to solve the same problem! Would love to have this merged asap as the capitalization has tripped me up multiple times 😄

**Comment by jasnonaz** [comment]
Hi @danieldiamond - thank you so much for contributing to dbt-utils! Given the duplicate PRs, we are going to close this and merge #403.

**Pull request closed without merging**
