### PR TITLE
Feature/safe divide

### LINKED ISSUE #679: Create a new safe divide cross db macro
### Describe the feature
I want to add a "safe divide" cross db macro (like [DIV0](https://docs.snowflake.com/en/sql-reference/functions/div0.html) in snowflake) to prevent errors when dividing by 0. 

### Who will this benefit?
Package developers - we're currently using nullif() on the denominator in dbt_project_evaluator package and would like to replace this with a simple safe divide macro. 

### Are you interested in contributing this feature?

Yes. I, @angelica-lastra, and @deanna-minnick will be collaborating on this!

### PR DESCRIPTION
**Pull request by deanna-minnick**
resolves #679 

This is a:
- [ ] documentation update
- [ ] bug fix with no breaking changes
- [x] new functionality
- [ ] a breaking change

All pull requests from community contributors should target the `main` branch (default).

## Description & motivation
 Created safe_divide macro to return null when dividing by 0 across all warehouses.

## Checklist
- [x] This code is associated with an Issue which has been triaged and [accepted for development](https://docs.getdbt.com/docs/contributing/oss-expectations#pull-requests). 
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [x] I followed guidelines to ensure that my changes will work on "non-core" adapters by:
    - [x] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/star.sql))
    - [ ] using the `limit_zero()` macro in place of the literal string: `limit 0`
    - [ ] using `dbt.type_*` macros instead of explicit datatypes (e.g. `dbt.type_timestamp()` instead of `TIMESTAMP`
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

### CODE REVIEW

**Review by b-per — APPROVED** [review]
Looks good to me!

**Review by dave-connors-3 — APPROVED** [review]
🦞 LGTM

**Review by graciegoheen — APPROVED** [review]
Let's goooooo!

**Comment by joellabes** [comment]
eek sorry that I hadn't gotten to this yet! It was on my queue 😅 This _should_ have targeted the utils-v1 branch - since we're still a few weeks from the final version 1.0 actually shipping it's probably worth reverting and merging into there instead, so that people don't get confused about why they can't use this yet. 

Also, it'd be good for the integration tests to include some expressions as well as just single column references, things like `{{ safe_divide(1, '2 * 0') }}`

**Pull request merged**
