### PR TITLE
Have union_relations raise exception when include parameter results in no columns

### LINKED ISSUE #266: Using union_relations macro with include paramater doesn't select any columns and results in error
### Describe the bug

I was successfully using the macro union_relations with the optional exclude parameter. However when I switched to using include I received the error 'SQL compilation error:
  syntax error line 19 at position 12 unexpected 'from'.' 
When I opened the compiled file I noticed that the compiled SQL wasn't selecting any of the columns I listed in the include paramater. It was only selecting the source model followed by a comma and the from statement thus triggering the SQL error. It appears the macro is not working as intended. 

### Steps to reproduce

Create a model using the union_relations macro and use the optional "include" parameter. List columns in the include parameter. I also renamed my source column, but I'm not sure if that is related to the bug.

### Expected results

I would expect all columns listed in the include parameter array to be in each select statement and not end in a comma before the from causing a syntax error. 

### Actual results

The macro is not calling any columns, but the source model column. I've confirmed these columns do exist in my underlying ref models and can query them from those tables in Snowflake.

### Screenshots and log output

Here is a screenshot of my model script:
Screen Shot 2020-08-13 at 3 27 21 PM

Here is a screenshot of part of the compiled script 
Screen Shot 2020-08-13 at 3 22 38 PM

Here is a screenshot of the error: 
Screen Shot 2020-08-13 at 3 32 37 PM

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0
   latest version: 0.17.2

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.17.0
  - snowflake: 0.17.0
  - redshift: 0.17.0
  - postgres: 0.17.0
```

**The operating system you're using:**
MacOS Mojave Version 10.14.6

**The output of `python --version`:**
Python 3.7.7

**Contents of packages:: **
  - package: fishtown-analytics/dbt_utils
    version: 0.5.1

### Are you interested in contributing the fix?

No, going on extended leave in a few weeks

### PR DESCRIPTION
**Pull request by grahamwetzler**
This is a:
- [ ] bug fix PR with no breaking changes — please ensure the base branch is `master`
- [ ] new functionality — please ensure the base branch is the latest `dev/` branch
- [x] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation

Fixes #266. Using the `include` parameter in `union_relations` with columns names that don't exist in the relations will result in invalid SQL being generated. This PR adds logic to raise an exception if there are no columns to union.

There doesn't appear to be a good way to write a unit test to ensure that an exception is raise (https://github.com/dbt-labs/dbt-core/issues/3060), but this worked in my manual testing.

## Checklist
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [x] Snowflake
- [ ] I followed guidelines to ensure that my changes will work on "non-core" adapters by:
    - [ ] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))
    - [ ] using the `limit_zero()` macro in place of the literal string: `limit 0`
    - [ ] using `dbt_utils.type_*` macros instead of explicit datatypes (e.g. `dbt_utils.type_timestamp()` instead of `TIMESTAMP`
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

### CODE REVIEW

**Comment by joellabes** [comment]
Hi @grahamwetzler, this makes a ton of sense! Thanks for making the change. I think that you're right that there's no way to expect a failure right now. The core team are giving this some thought at the moment though 🤞 

One nitpick: could you add the name of the affected model to the error message, to make it easier to track down? For some inspiration, check out https://github.com/dbt-labs/dbt-utils/blob/73a65562bf3d9b31a1eca0b27118056ad048d8fc/macros/cross_db_utils/_is_ephemeral.sql#L7-L12 (You won't need to pass in the calling macro name)

**Comment by grahamwetzler** [comment]
The new error message from my testing:
```
17:43:27  Encountered an error:
Runtime Error
  Compilation Error in model union_test (models/union_test.sql)
    There were no columns found to union for relations u1, u2
    
    > in macro default__union_relations (macros/sql/union.sql)
    > called by macro union_relations (macros/sql/union.sql)
    > called by model union_test (models/union_test.sql)
    > called by model union_test (models/union_test.sql)
```

**Comment by joellabes** [comment]
I like it! Could you add yourself to the changelog under the next patch release, and we'll get this merged in? 🎉

**Review by joellabes — APPROVED** [review]
Thank you so much for the contribution! 🥇

**Pull request merged**
