### PR TITLE
need col alias and flexible limit 0 clause

### PR DESCRIPTION
**Pull request by swanderz**
This is a:
- [x] bug fix PR with no breaking changes — please ensure the base branch is `master`
- [ ] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation

Changes to allow `tsql-utils` to upgrade to `dbt-utils>=0.7.0`

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake
- [ ] I have "dispatched" any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/star.sql))
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have added an entry to CHANGELOG.md

### CODE REVIEW

**Comment by joellabes** [comment]
Looks like a dupe of #437

**Comment by swanderz** [comment]
uh-oh @joellabes looks like September Anders knew more than November Anders. I need to column alias on the `else` clause too. shall I open another PR?

**Comment by joellabes** [comment]
Nah it's all good! I think the column alias was a red herring. it'd only be an issue if we were trying to `--store-failures` because then unnamed columns break (#430)

**Comment by swanderz** [comment]
> Nah it's all good! I think the column alias was a red herring. it'd only be an issue if we were trying to `--store-failures` because then unnamed columns break (#430)

what if I did something very hacky in dbt-sqlserver where a table is always created, but it's dropped after the test runs by default?

**Comment by joellabes** [comment]
Then we'd have a problem 😬  I'll fix it myself, don't worry about the overhead of a PR

**Comment by joellabes** [comment]
image


[Fixed here](https://github.com/dbt-labs/dbt-utils/commit/c2f228fce7d28d03755379fbea3b19f512cdd9ae)

**Pull request closed without merging**
