### PR TITLE
Fix link to macro section

### PR DESCRIPTION
**Pull request by clausherther**
This is a:
- [x] bug fix PR with no breaking changes — please ensure the base branch is `main`
- [ ] new functionality — please ensure the base branch is the latest `dev/` branch
- [ ] a breaking change — please ensure the base branch is the latest `dev/` branch

## Description & motivation
A couple of links are missing the `-source` suffix.

### CODE REVIEW

**Comment by clausherther** [comment]
Actually, also just realized there does not seem to be a README section for `listagg` even though the macro exists?

**Comment by judahrand** [comment]
#552

**Comment by dbeatty10** [comment]
> Actually, also just realized there does not seem to be a README section for `listagg` even though the macro exists?

Good catch, Claus! I just merged https://github.com/dbt-labs/dbt-utils/pull/560 which adds docs for `listagg`, and it will go out in the next release.

**Review by dbeatty10 — APPROVED** [review]
Thank you @clausherther  and @judahrand for updating this! 🌱

**Pull request merged**
