### PR TITLE
dbt utils v1.0.0-rc1

### PR DESCRIPTION
**Pull request by joellabes**
This is a:
- [ ] documentation update
- [ ] bug fix with no breaking changes
- [x] new functionality
- [x] a breaking change

All pull requests from community contributors should target the `main` branch (default).

## Description & motivation
Full migration guide to come 

## Checklist
- [x] This code is associated with an Issue which has been triaged and [accepted for development](https://docs.getdbt.com/docs/contributing/oss-expectations#pull-requests). 
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered)
    - [ ] BigQuery
    - [ ] Postgres
    - [ ] Redshift
    - [ ] Snowflake
- [x] I followed guidelines to ensure that my changes will work on "non-core" adapters by:
    - [x] dispatching any new macro(s) so non-core adapters can also use them (e.g. [the `star()` source](https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/star.sql))
    - [x] using the `limit_zero()` macro in place of the literal string: `limit 0`
    - [x] using `dbt.type_*` macros instead of explicit datatypes (e.g. `dbt.type_timestamp()` instead of `TIMESTAMP`
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have added an entry to CHANGELOG.md

### CODE REVIEW

**Comment by joellabes** [comment]
@dbeatty10 even though we discussed doing the release candidate from main, I didn't do that because those last two PRs weren't fully resolved yet and I figured it'd be easier to unwind anything you didn't agree with if it wasn't already on main. 

This PR is everything that's changed - either you or I have already reviewed each change independently, but might be useful for us to do one more check of the cohesive whole. Happy to either jump on a call or do it async as you prefer

**Review by dbeatty10 — APPROVED** [review]
### The Answer
🤓 This definitely feels like an answer:

image

### The Review

> either you or I have already reviewed each change independently, but might be useful for us to do one more check of the cohesive whole

👍 But in all seriousness, if each change has already been reviewed by a maintainer, then I'm all for merging as-is.

I'm assuming that doing so would allow all dev work going forward to be on the `main` branch again?

### Proposed follow-up item

As a follow-up item, it would be worth viewing each of the PRs that were merged to the `utils-v1` branch and confirm their associated issues are closed.

**Comment by joellabes** [comment]
> I'm assuming that doing so would allow all dev work going forward to be on the `main` branch again?

Indeed! Our long national nightmare is finally over 🎉 

> confirm their associated issues are closed.

Good idea 🫡

**Comment by Vignesh-Pitchaiah** [comment]
Try adding Distinct in select query to this, it helps in optimizing the sql run

**Comment by Vignesh-Pitchaiah** [comment]
Can you use distinct in inner select clause, cause it will improve the sql and optimize the search

**Comment by dbeatty10** [comment]
@Vignesh-Pitchaiah that sounds like a either a feature request or bug report related to the [`recency `](https://github.com/dbt-labs/dbt-utils/blob/6ba7b660b1d1b4e3b41cb0cf6c3c0e4a70ae54e4/macros/generic_tests/recency.sql) generic test.

Could you open an issue [here](https://github.com/dbt-labs/dbt-utils/issues/new/choose) with all the relevant details?

**Pull request merged**
